@MyShorty.Api_HostAddress = http://localhost:5000

POST {{MyShorty.Api_HostAddress}}/generateShortUrl/
Accept: application/json
Content-Type: application/json

{
  "Url": "https://bowscore.leansparkdigital.com/"
}

###
POST {{MyShorty.Api_HostAddress}}/generateShortUrl/
Accept: application/json
Content-Type: application/json

{
  "Url": "https://www.google.com/"
}

###
POST {{MyShorty.Api_HostAddress}}/generateShortUrl/
Accept: application/json
Content-Type: application/json

{
  "Url": "https://bowscore.leansparkdigital.com/practice"
}